Adding support for in-source builds
rrdelaney/bs-loader pull request #24
Opened 2017-09-02 23:07 UTC by arnarthor

This adds a check for in-source builds. 

There is one caveat to this PR that I would like to discuss. Since this uses `require` to read the bsconfig to check if the build should be done in-source, it requires the bsconfig to be valid JSON, which is not required by bucklescript since it ships it's own JSON parser.

If there's some way to use that JSON parser instead that would be great, otherwise this would need to be a limitation of using bs-loader (which IMO is fine, but could be confusing).

2017-09-03 19:26 UTC, rrdelaney commented
Don't worry about the Travis build failing, there's some permission problems on the CI 😄

2017-09-03 19:30 UTC, rrdelaney requested changes
Thanks so much 😄 

I think we can skip parsing the bsconfig for now and just use a Webpack setting for in-source, maybe a separate release for reading config from the bsconfig

2017-09-03 19:30 UTC, rrdelaney commented on index.js
> +const isInSourceBuild = moduleOptions => {
Can we use a Webpack config option instead like we do with the `module` field? We can switch both the reading the `bsconfig.json` at a later time

2017-09-03 19:36 UTC, arnarthor commented
Yeah that sounds good 👍. We should probably document it then to make sure people don't forget to change their bsconfig when using this.

I'll add something about it as well.

2017-09-04 00:42 UTC, arnarthor commented
I've fixed what we discussed (except I forgot to add docs). For some reason I can't get the tests to run locally any more (not even before I made the change). 

Anyways, this should be equivalent to the bsconfig parsing thing I did before. 👍

2017-09-04 01:04 UTC, rrdelaney approved these changes

2017-09-04 01:41 UTC, rrdelaney commented
I'm just gonna see if I can get the tests running locally, then merge this in!

2017-09-04 18:46 UTC, merged